config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :homeworks
  patch 'homeworks/complete/:id' => 'homeworks#complete', as: 'complete_homework'
  resources :students
  resources :lessons

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.is_admin?
        can :manage, :all
      else
        can :read, :all
      end

      
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/completed.rb
class Completed < ActiveRecord::Base
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  belongs_to :lesson
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_and_belongs_to_many :students
  has_many :homeworks
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_and_belongs_to_many :lessons

  validates :school_number, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  rescue_from CanCan::AccessDenied do |exception|
   redirect_to main_app.root_url, :alert => exception.message
 end
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: [:show, :edit, :update, :destroy, :complete]

  def index
    @homeworks = Homework.all
  end


  def show
  end

  def new
    @homework = Homework.new
  end

  def edit
  end

  def create
    @homework = Homework.new(homework_params)
      if @homework.save
        redirect_to @homework, notice: 'Homework was successfully created.'
      else
        render :new
      end
  end

  def update
      if @homework.update(homework_params)
        redirect_to @homework, notice: 'Homework was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @homework.destroy
    redirect_to homeworks_url, notice: 'Homework was successfully destroyed.'
  end

  def complete
    Completed.create(user_id: current_user.id, homework_id: @homework.id, completed_at: Date.today)
    redirect_to @homework, notice: 'Homework completed successfully.'
  end

  private
    def set_homework
      @homework = Homework.find(params[:id])
    end

    def homework_params
      params.require(:homework).permit(:lesson_id, :subject, :content, :start_time, :end_time)
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  def index
    @lessons = Lesson.all
  end

  def show
  end

  def new
    @lesson = Lesson.new
  end

  def edit
  end

  def create
    @lesson = Lesson.new(lesson_params)
      if @lesson.save
        redirect_to @lesson, notice: 'Lesson was successfully created.'
      else
        render :new
      end
  end

  def update
      if @lesson.update(lesson_params)
        redirect_to @lesson, notice: 'Lesson was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @lesson.destroy
      redirect_to lessons_url, notice: 'Lesson was successfully destroyed.'
    end

  private
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:lesson_code, :teacher_id, :student_id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
    @completeds = Completed.where(user_id: current_user.id)
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

      if @student.save
        redirect_to @student, notice: 'Student was successfully created.'
      else
        render :new
      end
  end

  def update
      if @student.update(student_params)
        redirect_to @student, notice: 'Student was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @student.destroy
      redirect_to students_url, notice: 'Student was successfully destroyed.'
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :age, :degree)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :get_student

  def index
    if @student == nil
      @lessons = Lesson.where(teacher_name: current_user.name)
    else
      @lessons = @student.lessons
    end
  end

  private
  def get_student
    @student = Student.find_by(school_number: current_user.school_number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/homeworks/_form.html.erb
<div class="row">
<%= form_for(@homework) do |f| %>
  <% if @homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
      <% @homework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




    <div class="large-6 large-centered columns">
        <%= f.label :subject %><br>
        <%= f.text_field :subject %>

    </div>



  <div class="large-6 large-centered columns">
    <%= f.label :content %>
    <%= f.trix_editor :content %>
  </div>

  <br>

  <div class="large-6 large-centered columns">

      <div class="large-6 columns">
        <%= f.label :start_time %><br>
        <%= f.date_select :start_time %>
      </div>
      <div class="large-6 columns">
        <%= f.label :end_time %><br>
        <%= f.date_select :end_time %>
      </div>
      <%= f.select :lesson_id, Lesson.where(teacher_name: current_user.name).collect {|x| [x.lesson_code, x.id]}, {} %>
      <%= f.submit "Submit", {:class => 'button'} %>
  </div>


  <div class="actions">

  </div>
<% end %>
</div>

app/views/homeworks/edit.html.erb
<h1>Editing Homework</h1>

<%= render 'form' %>

<%= link_to 'Show', @homework %> |
<%= link_to 'Back', homeworks_path %>

app/views/homeworks/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>

  <h1>Listing Homeworks</h1>

  <table>
    <thead>
      <tr>
        <th>Lesson</th>
        <th>Subject</th>
        <th>Content</th>
        <th>Start time</th>
        <th>End time</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @homeworks.each do |homework| %>
        <tr>
          <td><%= homework.lesson.lesson_code %></td>
          <td><%= homework.subject %></td>
          <td><%= homework.content %></td>
          <td><%= homework.start_time %></td>
          <td><%= homework.end_time %></td>
          <td><%= link_to 'Show', homework, {:class => 'button'} %></td>
          <td><%= link_to 'Edit', edit_homework_path(homework), {:class => 'button'} %></td>
          <td><%= link_to 'Destroy', homework, {method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button'} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Homework', new_homework_path,  {:class => 'button'} %>

</div>

app/views/homeworks/new.html.erb
<h1>New Homework</h1>

<%= render 'form' %>

<%= link_to 'Back', homeworks_path, {:class => 'button'} %>

app/views/homeworks/show.html.erb
<div class="row">

  <div class="large-6 large-centered columns" style="text-align: center;">
    <h3>
      <strong>Lesson:</strong>
      <%= @homework.lesson.lesson_code %>
    </h3>

    <h5>Subject: <%= @homework.subject %> </h5>
<br>
    <%= raw @homework.content %>
    <br><br><br>
  </div>

  <div class="large-6 large-centered columns" style="text-align: center;">


      <div class="large-6 columns">
        <p>
          <strong>Start time:</strong>
          <%= @homework.start_time.strftime("%Y/%m/%d")%>
        </p>
      </div>

      <div class="large-6 columns">
        <p>
          <strong>End time:</strong>
          <%= @homework.end_time.strftime("%Y/%m/%d") %>
        </p>

      </div>


  </div>


  <%= link_to "Back", :back, {:class => 'button'} %>
  <% if current_user.is_teacher != 1 %>
    <% if Completed.where(user_id: current_user.id, homework_id: @homework.id).any? %>
      <%= link_to "Already Completed", "#", {:class => 'disabled button'}%>
    <% else %>
      <%= link_to "Complete", complete_homework_path,{ method: :patch, :class => 'button'}%>
    <% end %>
  <% else %>
    <%= link_to "Edit Homework", edit_homework_path(@homework), {:class => 'button'} %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Peyneith Homework System" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="top-bar">
      <div class="top-bar-title">
        <%= link_to image_tag("logo2.png"), root_path %>
      </div>
      <div id="responsive-menu">
        <div class="top-bar-left">
          <% if user_signed_in? %>
              <ul class="menu">
                <% if current_user.is_teacher == 1 %>
                <li><%= link_to "New Homework", new_homework_path, {:class => ' button  '} %></li>
                <% end %>
              </ul>
          <% end %>
        </div>
        <div class="top-bar-right">
          <ul class="menu">
            <% if  user_signed_in? %>
              <% if current_user.is_admin? %>
                <li><%= link_to "Admin Panel", rails_admin.dashboard_path, {:class => 'button alert'} %></li>
                <li style="background-color: rgba(33, 153, 232, 0.44);">&nbsp;</li>
              <% end %>
              <li><%= link_to "My Profile", edit_user_registration_path(current_user), {:class => 'success button'} %></li>
              <li style="background-color: rgba(33, 153, 232, 0.44);">&nbsp;</li>
              <li><%= link_to "Log Out",destroy_user_session_path, {:class => 'alert button', :method => 'DELETE'} %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path, {:class => 'button'} %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="row">
      <p id="notice"><%= notice %></p>

        <%= yield %>
        <br>

    </div>

    <footer class="footer">
      <div class="row column">
     <hr>
     <ul class="menu">
        <li>Peyneith Homework System</li>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About' %></li>
        <li><%= link_to 'Contact'%></li>
        <li class="float-right">Copyright 2016</li>
     </ul>
  </div>
  </footer>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lesson_code %><br>
    <%= f.text_field :lesson_code %>
  </div>
  <div class="field">
    <%= f.label :teacher_name %><br>
    <%= f.text_field :teacher_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>

  <h1>Listing Lessons</h1>

  <table>
    <thead>
      <tr>
        <th>Lesson code</th>
        <th>Teacher</th>
        <th>Student Count</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @lessons.each do |lesson| %>
        <tr>
          <td><%= lesson.lesson_code %></td>
          <td><%= lesson.teacher_name %></td>
          <td><%= lesson.students.count %></td>
          <td><%= link_to 'Show', lesson, {:class => "button"} %></td>
          <td><%= link_to 'Edit', edit_lesson_path(lesson), {:class => 'button'} %></td>
          <td><%= link_to 'Destroy', lesson, {method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button'} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Lesson', new_lesson_path, {:class => "button"} %>

</div>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

    <h3>Lesson: <%= @lesson.lesson_code %></h3>
    <h4>Homeworks for this lesson</h2>
      <table>
        <thead>
          <tr>
            <th>Subject</th>
            <th>Start time</th>
            <th>End time</th>
            <th>Student Count</th>
            <% if current_user.is_teacher != 1 %>
              <th>Is it Completed?</th>
            <% end %>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @lesson.homeworks.each do |homework| %>
            <tr>
              <td><%= homework.subject %></td>
              <td><%= homework.start_time.strftime("%Y/%m/%d") %></td>
              <td><%= homework.end_time.strftime("%Y/%m/%d") %></td>
              <td><%= Completed.where(homework_id: homework.id).count %></td>
              <% if current_user.is_teacher != 1 %>
                <td><%= Completed.where(user_id: current_user.id, homework_id: homework.id).any?.to_s.capitalize %></td>
              <% end %>
              <td><%= link_to 'Show', homework,  {:class => 'button'} %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

  <br>
  <br>

</div>

<%= link_to "Back", :back, {:class => 'button'} %>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :degree %><br>
    <%= f.number_field :degree %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>

  <h1>Listing Students</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Degree</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.name %></td>
          <td><%= student.age %></td>
          <td><%= student.degree %></td>
          <td><%= link_to 'Show', student, {:class => 'button'} %></td>
          <td><%= link_to 'Edit', edit_student_path(student), {:class => 'button'} %></td>
          <td><%= link_to 'Destroy', student, { method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Student', new_student_path, {:class => "button"} %>

</div>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<div class="row">

  <div class="large-6 large-centered columns">
    <canvas id="myChart" width="200" height="200"></canvas>
  </div>

  <script>

  var ctx = document.getElementById("myChart").getContext("2d");
  var myChart = new Chart(ctx, {
      type: 'bar',
      data: {
          labels: [
            <% @completeds.each do |completed| %>
              "<%= Homework.find(completed.homework_id).lesson.lesson_code %>",
            <% end %>
          ],
          datasets: [{
              label: '# of Homeworks Completed',
              data: [
                <% Student.find_by(school_number: current_user.school_number).lessons.each do |lesson| %>
                <% count = 0 %>
                  <% lesson.homeworks.each do |homework| %>
                    <% if Completed.where(user_id: current_user.id, homework_id: homework.id).any? %>
                      <% count = count + 1 %>
                    <% end %>
                  <% end %>
                  "<%= count %>",
                <% end %>
              ]
          }]
      }
  });
  </script>
</div>

<%= link_to 'Back', root_path,  {:class => 'button'} %>

app/views/welcome/index.html.erb
  <div class="row">
  <% if Student.where(school_number: current_user.school_number).any? %>
  <h2>Welcome <%= current_user.name %>!</h2>
  Your Student Number: <%= current_user.school_number %>
  <h3>Your Lessons</h3>
  <table>
    <thead>
      <tr>
        <th>Lesson code</th>
        <th>Teacher</th>
        <th>Student Count</th>
        <th>Homeworks</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @lessons.each do |lesson| %>
        <tr>
          <td><%= lesson.lesson_code %></td>
          <td><%= lesson.teacher_name %></td>
          <td><%= lesson.students.count %></td>
          <td><%= lesson.homeworks.count %></td>
          <td><%= link_to 'Show', lesson,  {:class => 'button'} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% else %>
    <h2>Welcome <%= current_user.name %></h2>
    <h3>Your Lessons</h3>
    <table>
      <thead>
        <tr>
          <th>Lesson code</th>
          <th>Teacher</th>
          <th>Student Count</th>
          <th>Homeworks</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @lessons.each do |lesson| %>
          <tr>
            <td><%= lesson.lesson_code %></td>
            <td><%= lesson.teacher_name %></td>
            <td><%= lesson.students.count %></td>
            <td><%= lesson.homeworks.count %></td>
            <td><%= link_to 'Show', lesson,  {:class => 'button'} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>